### ISSUE TITLE
Study performance loss in anomaly calculation

### ISSUE THREAD

**Issue by kmpaul** [pangeo-data/benchmarking#29]
SC Paper showed poor scaling for spatially chunked data when doing the anomaly operation.  Why?

**Comment by tinaok** [comment]
I suppose that is due to unoptimised  chunk size
I created a branch with 'debug' in my repo.  There for each operation, it shows dataset information with chunk size.  I created a table from output of debug information as follows. 
https://github.com/tinaok/benchmarking/blob/debug/chunksize.md

I see two reasons by looking at chunk size.

1. Climate data set only have 4 time coordinate, and It is chunked in '1'.  If it was duplicated for each workers with all 4 time coordinated, and broad casted  that would speed up the computation for anomaly operation.

1. Anomaly data set chunk size: time coordinate is chunked in '60'.  Why? I do not understand.  it looks like it heritage the chunk size of lat and lon coordinate from 'sst', but not for the size of time coordinate.  Thus for spatial time coordinate, each chunk get really small which would slow down the process.

Are these problem comes from Dask? or Xarray?
May be we would need to make small 'reproducing code' to investigate. (also to understand  #issue #30 )

**Comment by tinaok** [comment]
Hi i made small code here https://gist.github.com/tinaok/c2ef193e94508a5ba426979d01e99307#file-anomaly-chunksizesimplifyed-ipynb 
anomaly-chunksizesimplifyed show that if frequency of time is setted as '1D' each chunk of anomaly array have all the same season in the same chunk.   thus why time have 60 as chunksize on time coordinate. 
(i.e. if you modify the frequency from '1D' to '1H' it will change the chunksize to 1444 )

But this is not optimal in term of this computation.  it should broadcast climate data rather than chunking data in each season...

**Comment by kmpaul** [comment]
I believe this is pretty well understood, now.  I think we can now attribute it to the re-chunking behavior of `groupby`, correct?
